import 'package:flutter/widgets.dart';

import 'app_language.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('fr'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations =
        Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  bool get isFrench => locale.languageCode == 'fr';
  AppLanguage get language => AppLanguage.fromCode(locale.languageCode);

  static const Map<String, String> _en = {
    'startup_failed': 'Startup failed',
    'home': 'Home',
    'search': 'Search',
    'chat': 'Chat',
    'alerts': 'Alerts',
    'options': 'Options',
    'filters': 'Filters',
    'clear': 'Clear',
    'marketplace': 'Marketplace',
    'gigs': 'Gigs',
    'foods': 'Foods',
    'businesses': 'Businesses',
    'restaurants': 'Restaurants',
    'my_profile': 'My profile',
    'admin_portal': 'Admin portal',
    'logout': 'Logout',
    'more': 'More',
    'notifications': 'Notifications',
    'messages': 'Messages',
    'logout_failed': 'Logout failed: {error}',
    'edit_profile': 'Edit profile',
    'edit_profile_intro':
        'Update your identity, categories, location, and feed settings in one place.',
    'tap_to_change_avatar': 'Tap to change avatar',
    'avatar_updated': 'Avatar updated',
    'postal_code_locked': 'Postal code is locked after first set.',
    'postal_code_required':
        'Enter a valid 5-digit French postal code (e.g. 91000)',
    'geocoding_failed': 'Geocoding failed (HTTP {status}). Try again.',
    'postal_code_not_found': 'Postal code not found. Try another one.',
    'invalid_coordinates':
        'Geocoding returned invalid coordinates. Try another zip.',
    'location_set_city': 'Location set for {zip} • {city}',
    'location_set_zip_only':
        'Location set for {zip}. Add your city manually if needed.',
    'not_logged_in': 'Not logged in',
    'name_required': 'Name is required',
    'set_location_first': 'Please set your location (zip code) first',
    'city_required': 'City is required',
    'select_org_type': 'Please select Government, Non-profit, or News agency',
    'select_restaurant_type': 'Please select restaurant type',
    'select_business_type': 'Please select business type',
    'saving': 'Saving...',
    'save': 'Save',
    'account_type': 'Account type',
    'person': 'Person',
    'business': 'Business',
    'organization': 'Organization',
    'are_you_restaurant': 'Are you a restaurant?',
    'restaurant_category': 'Restaurant category',
    'business_category': 'Business category',
    'business_name': 'Business name',
    'organization_name': 'Organization name',
    'your_title': 'Your title (Founder, Owner, Manager...)',
    'short_business_profile': 'Short business profile',
    'short_organization_profile': 'Short organization profile',
    'describe_business': 'Briefly describe your business',
    'describe_organization': 'Briefly describe your organization',
    'organization_type': 'Organization type',
    'government': 'Government',
    'non_profit': 'Non-profit',
    'news_agency': 'News agency',
    'name': 'Name',
    'bio_optional': 'Bio (optional)',
    'postal_code': 'Postal code',
    'postal_code_hint': 'e.g. 91000',
    'locked_after_first_set': 'Locked after first set',
    'set': 'Set',
    'set_done': 'Set ✓',
    'city': 'City',
    'city_hint': 'Auto-filled from postal code, or enter manually',
    'city_lat_lng': 'City: {city} • Lat/Lng: {lat}, {lng}',
    'lat_lng': 'Lat/Lng: {lat}, {lng}',
    'feed_radius': 'Feed radius',
    'app_language': 'App language',
    'english': 'English',
    'french': 'French',
    'public': 'Public',
    'share': 'Share',
    'local': 'Local',
    'visibility': 'Visibility',
    'no_sharing': 'No sharing',
    'followers_can_share': 'Followers can share',
    'connections_can_share': 'Connections can share',
    'public_can_share': 'Public can share',
    'allow_sharing': 'Allow sharing',
    'complete_profile': 'Complete Profile',
    'profile': 'Profile',
    'profile_error': 'Profile error:\n{error}',
    'type': 'Type: {value}',
    'location': 'Location: {value}',
    'followers': 'Followers',
    'following': 'Following',
    'connections': 'Connections',
    'followers_following_private': 'Followers/Following lists are private.',
    'message': 'Message',
    'message_after_mutual_follow':
        'Message is available after you both follow each other.',
    'organization_government': 'Organization • Government',
    'organization_nonprofit': 'Organization • Non-profit',
    'organization_news_agency': 'Organization • News agency',
    'restaurant': 'Restaurant',
    'profile_actions': 'Profile actions',
    'follow_requests': 'Follow requests',
    'follow_requests_pending': '{count} pending requests',
    'review_incoming_requests': 'Review incoming requests',
    'update_details_location': 'Update your details and location',
    'profile_settings': 'Profile settings',
    'manage_app_preferences': 'Manage app preferences like video autoplay',
    'followers_count_subtitle': '{count} people follow you',
    'following_count_subtitle': '{count} profiles you follow',
    'connections_count_subtitle': '{count} people follow you back',
    'my_products': 'My products',
    'edit_delete_marketplace_ads': 'Edit or delete your marketplace ads',
    'my_gigs': 'My gigs',
    'edit_delete_service_ads': 'Edit or delete your service ads',
    'my_foods': 'My foods',
    'edit_delete_food_ads': 'Edit or delete your food ads',
    'visible_only_own_profile': 'Visible only on your own profile',
    'profile_overview': 'Profile overview',
    'this_is_your_profile': 'This is your profile',
    'delete_post': 'Delete post?',
    'delete_post_body':
        'This will remove the post from your profile and feed.',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'post_deleted': 'Post deleted.',
    'delete_failed': 'Delete failed: {error}',
    'follow_error': 'Follow error: {error}',
    'unfollow': 'Unfollow',
    'requested': 'Requested',
    'request_again': 'Request again',
    'request_follow': 'Request follow',
    'remove_photo': 'Remove photo?',
    'remove_photo_body': 'This will remove it from your portfolio.',
    'remove': 'Remove',
    'portfolio_error': 'Portfolio error:\n{error}',
    'portfolio': 'Portfolio',
    'add': 'Add',
    'add_portfolio_photos': 'Add up to 5 photos to your portfolio.',
    'no_portfolio_photos': 'No portfolio photos yet.',
    'replace_photo': 'Replace photo',
    'remove_photo_tooltip': 'Remove photo',
    'portfolio_upload_error': 'Portfolio upload error: {error}',
    'portfolio_delete_error': 'Portfolio delete error: {error}',
    'portfolio_update_error': 'Portfolio update error: {error}',
    'playback': 'Playback',
    'playback_subtitle': 'Control how videos behave across the app.',
    'video_auto_play': 'Video auto play',
    'video_auto_play_subtitle':
        'Videos start playing automatically when enabled.',
    'in_app_notifications': 'In-app notifications',
    'in_app_notifications_subtitle':
        'Choose which updates should appear inside the app.',
    'push_notifications': 'Push notifications',
    'push_notifications_subtitle':
        'Saved now for future mobile and web push support.',
    'failed_to_save_setting': 'Failed to save setting: {error}',
    'chat_messages': 'Chat messages',
    'chat_messages_subtitle':
        'Show live in-app alerts for direct chat messages.',
    'offer_messages': 'Offer messages',
    'offer_messages_subtitle':
        'Show notifications for listing conversation messages.',
    'offer_updates': 'Offer updates',
    'offer_updates_subtitle':
        'Show sent, accepted, and rejected offer updates.',
    'comments_on_my_posts': 'Comments on my posts',
    'comments_on_my_posts_subtitle':
        'Notify you when someone comments on your content.',
    'replies_to_my_comments': 'Replies to my comments',
    'replies_to_my_comments_subtitle':
        'Notify you when someone replies to your comment or question.',
    'mentions': 'Mentions',
    'mentions_subtitle':
        'Notify you when someone tags you in a post or comment.',
    'follow_requests_subtitle':
        'Notify you when someone requests to follow you.',
    'new_followers': 'New followers',
    'new_followers_subtitle':
        'Notify you when someone follows you or accepts your request.',
    'admin_and_safety_updates': 'Admin and safety updates',
    'admin_and_safety_updates_subtitle':
        'Show account, moderation, and safety-related updates.',
    'push_chat_messages': 'Push chat messages',
    'push_chat_messages_subtitle':
        'Reserved for future mobile and web push support.',
    'push_offer_messages': 'Push offer messages',
    'push_offer_messages_subtitle':
        'Reserved for future push notifications on offer chats.',
    'push_offer_updates': 'Push offer updates',
    'push_offer_updates_subtitle':
        'Reserved for offer sent, accepted, and rejected pushes.',
    'push_comments': 'Push comments',
    'push_comments_subtitle':
        'Reserved for future push notifications on comments.',
    'push_replies': 'Push replies',
    'push_replies_subtitle':
        'Reserved for future push notifications on replies.',
    'push_mentions': 'Push mentions',
    'push_mentions_subtitle':
        'Reserved for future push notifications on mentions.',
    'push_follow_requests': 'Push follow requests',
    'push_follow_requests_subtitle':
        'Reserved for future push notifications on follow requests.',
    'push_new_followers': 'Push new followers',
    'push_new_followers_subtitle':
        'Reserved for future push notifications on follows.',
    'push_admin_updates': 'Push admin and safety updates',
    'push_admin_updates_subtitle':
        'Reserved for important admin and safety pushes.',
    'account_disabled_contact_admin':
        'This account has been disabled. Contact an administrator.',
    'google_tokens_missing':
        'Google sign-in did not return the required tokens.',
    'sign_in_failed': 'Sign in failed',
    'welcome_to': 'Welcome to',
    'login_intro':
        'Neighborhood updates, marketplace deals, gigs, food ads, and local conversations in one place.',
    'nearby_posts': 'Nearby posts',
    'offer_chats': 'Offer chats',
    'local_services': 'Local services',
    'welcome_back': 'Welcome back',
    'sign_in_to_network': 'Sign in to continue to your local network.',
    'email': 'Email',
    'password': 'Password',
    'forgot_password': 'Forgot password?',
    'signing_in': 'Signing in...',
    'sign_in': 'Sign in',
    'continue_with_google': 'Continue with Google',
    'create_account_cta': 'Create an account',
    'join': 'Join',
    'register_intro':
        'Create your account and start discovering nearby posts, local offers, food ads, and trusted community updates.',
    'create_profile': 'Create profile',
    'share_locally': 'Share locally',
    'find_nearby_deals': 'Find nearby deals',
    'chat_safely': 'Chat safely',
    'check_your_email': 'Check your email',
    'verification_email_sent':
        'We sent a confirmation email to {email}. Enter the 6-digit code from the email below, or click the link inside it.',
    'enter_verification_code': 'Enter the 6-digit code from your email',
    'verification_code': 'Verification code',
    'verify_email': 'Verify',
    'verifying': 'Verifying...',
    'verification_success': 'Email verified! You can now log in.',
    'invalid_otp_code': 'Invalid or expired code. Check your email and try again.',
    'return_to_login': 'Return to login',
    'create_account': 'Create account',
    'start_local_profile': 'Start your local profile in a few seconds.',
    'creating': 'Creating...',
    'sign_up_failed': 'Sign up failed',
    'email_exists_login':
        'An account with this email already exists. Please log in instead.',
    'back_to_login': 'Back to login',
    'enter_email_address': 'Enter your email address',
    'reset_failed': 'Reset failed: {error}',
    'reset_password': 'Reset your password',
    'reset_password_intro':
        'Enter the email address linked to your account.',
    'reset_link_sent_if_exists':
        'If an account exists for {email}, you will receive a password reset link shortly.',
    'sending': 'Sending...',
    'send_reset_link': 'Send reset link',
    'set_new_password': 'Set a new password',
    'set_new_password_intro':
        'Choose a secure password for your account.',
    'password_min_length': 'Password must be at least 6 characters',
    'passwords_do_not_match': 'Passwords do not match',
    'password_updated_successfully': 'Password updated successfully',
    'new_password': 'New password',
    'confirm_password': 'Confirm password',
    'update_password': 'Update password',
    'notifications_intro':
        'Stay on top of follows, messages, offers, and updates.',
    'mark_all_read': 'Mark all read',
    'load_more_failed': 'Load more failed: {error}',
    'failed_generic': 'Failed: {error}',
    'nothing_to_open': 'Nothing to open',
    'request_accepted': 'Request accepted',
    'accept_failed': 'Accept failed: {error}',
    'request_declined': 'Request declined',
    'decline_failed': 'Decline failed: {error}',
    'accept': 'Accept',
    'decline': 'Decline',
    'someone': 'Someone',
    'seller': 'Seller',
    'author': 'Author',
    'notif_follow_request': '{name} requested to follow you',
    'notif_follow_accepted': '{name} accepted your follow request',
    'notif_follow': '{name} started following you',
    'notif_like': '{name} liked your post',
    'notif_listing_question': '{name} asked a question on your listing',
    'notif_comment': '{name} commented on your post',
    'notif_comment_like': '{name} liked your comment',
    'notif_listing_reply': '{name} replied to your question',
    'notif_comment_reply': '{name} replied to your comment',
    'notif_share': '{name} shared your post',
    'notif_tagged_comment': '{name} tagged you in a comment',
    'notif_tagged_post': '{name} tagged you in a post',
    'notif_offer_message': '{name} sent a message about your listing',
    'notif_offer_sent': '{name} sent an offer on your listing',
    'notif_offer_accepted': '{name} accepted the offer',
    'notif_offer_rejected': '{name} rejected the offer',
    'notif_generic_update': '{name} sent an update',
    'unread': 'Unread',
    'tap_to_open': 'Tap to open',
    'no_notifications_yet': 'No notifications yet',
    'scroll_down_load_more': 'Scroll down to load more',
    'hide_search_filters': 'Hide search filters',
    'show_search_filters': 'Show search filters',
    'profiles': 'Profiles',
    'posts': 'Posts',
    'nearby_only': 'Nearby only',
    'loading_your_location': 'Loading your location...',
    'global_search': 'Global search',
    'location_not_set_fallback':
        'Location not set in your profile (fallback to global search)',
    'using_profile_radius': 'Using your profile radius: {radius} km',
    'match_strictness': 'Match strictness',
    'broad': 'Broad',
    'balanced': 'Balanced',
    'precise': 'Precise',
    'exact': 'Exact',
    'broader': 'Broader',
    'this_changes_match_quality':
        'This changes match quality only. Distance is controlled by Nearby only.',
    'scope': 'Scope',
    'post_type': 'Post Type',
    'author_type': 'Author Type',
    'retry': 'Retry',
    'type_something_to_search': 'Type something to search.',
    'no_profiles_found': 'No profiles found.',
    'unnamed': 'Unnamed',
    'no_posts_found': 'No posts found.',
    'no_text': '(no text)',
    'search_profiles_or_posts': 'Search profiles or posts...',
    'all': 'All',
    'service_offer': 'Offering',
    'service_request': 'Requesting',
    'lost_found': 'Lost & found',
    'post_shared': 'Post shared',
    'share_error': 'Share error: {error}',
    'like_error': 'Like error: {error}',
    'discover_nearby': 'Discover nearby',
    'feed_controls': 'Feed controls',
    'close': 'Close',
    'reset': 'Reset',
    'general_posts': 'General posts',
    'normal_feed_posts_only': 'Normal feed posts only.',
    'marketplace_posts': 'Marketplace posts',
    'buying_selling_product_categories':
        'Buying, selling, and product categories.',
    'marketplace_categories': 'Marketplace categories',
    'select_at_least_one_category': 'Select at least one category.',
    'gig_posts': 'Gig posts',
    'service_offers_requests_and_categories':
        'Service offers, requests, and service categories.',
    'gig_type': 'Gig type',
    'offering': 'Offering',
    'requesting': 'Requesting',
    'service_categories': 'Service categories',
    'lost_and_found': 'Lost & found',
    'show_or_hide_lost_and_found_posts': 'Show or hide lost-and-found posts.',
    'food_ads': 'Food ads',
    'food_posts_with_separate_categories':
        'Food posts with separate food categories.',
    'organization_types': 'Organization types',
    'show_organization_posts_by_subtype':
        'Show organization posts by subtype.',
    'select_at_least_one_type': 'Select at least one type.',
    'apply_filters': 'Apply filters',
    'visibility_public_following': 'Public + Following',
    'browse_sections': 'Browse sections',
    'open_filters': 'Open filters',
    'post_to_feed': 'Post to feed',
    'reset_feed': 'Reset feed',
    'local_directory': 'Local directory',
    'browse_nearby_places_to_eat': 'Browse nearby places to eat.',
    'explore_nearby_local_businesses': 'Explore nearby local businesses.',
    'top_trending': 'Top Trending',
    'no_top_posts_yet': 'No top posts yet',
    'engagement_count': '{count} engagement',
    'todo': 'To do',
    'review_offers': 'Review offers',
    'conversations_need_attention': '{count} conversations need attention.',
    'unread_offer_messages': 'Unread offer messages',
    'unread_messages_in_offer_chats':
        '{count} unread messages in offer chats.',
    'unread_notifications': '{count} unread notifications.',
    'unread_chats': 'Unread chats',
    'unread_conversations': '{count} unread conversations.',
    'nothing_pending_right_now': 'Nothing pending right now.',
    'profile_completeness': 'Profile completeness',
    'profile_complete_percent': '{count}% complete',
    'improve_trust_and_discovery':
        'Add the missing profile details to improve trust and discovery.',
    'open_profile': 'Open profile',
    'open_original': 'Open original',
    'feed_error': 'Feed error:\n{error}',
    'no_sections_selected': 'no sections selected',
    'you_are_seeing': 'You are seeing {sections}',
    'you_are_seeing_with_radius':
        'You are seeing {sections}. Public posts radius is set in profile: {radius} km',
    'all_marketplace_posts': 'all marketplace posts',
    'no_categories_selected': 'no categories selected',
    'all_gigs': 'all gigs',
    'gigs_in_categories': 'gigs {types} in {categories}',
    'food_ads_in_categories': 'food ads in {categories}',
    'all_organization_posts': 'all organization posts',
    'sell_buy': 'Sell / Buy',
    'search_products_category_seller':
        'Search products, category, seller...',
    'category_label': 'Category:',
    'type_label': 'Type:',
    'sort_label': 'Sort:',
    'all_categories': 'All categories',
    'all_types': 'All types',
    'newest_first': 'Newest first',
    'oldest_first': 'Oldest first',
    'price_low_to_high': 'Price: low to high',
    'price_high_to_low': 'Price: high to low',
    'no_marketplace_posts_found': 'No marketplace posts found',
    'looking_to_buy': 'Looking to buy',
    'price_on_request': 'Price on request',
    'post_a_service': 'Post a Service',
    'search_services_category_provider':
        'Search services, category, provider...',
    'with_price': 'With price',
    'without_price': 'Without price',
    'no_service_posts_found': 'No service posts found',
    'budget_open': 'Budget open',
    'rate_on_request': 'Rate on request',
    'send_offer': 'Send offer',
    'search_foods_category_restaurant':
        'Search foods, category, restaurant...',
    'all_food_categories': 'All food categories',
    'sort_by': 'Sort by',
    'no_food_ads_found': 'No food ads found',
    'search_businesses': 'Search businesses...',
    'distance_label': 'Distance:',
    'no_businesses_found': 'No businesses found',
    'search_restaurants': 'Search restaurants...',
    'no_restaurants_found': 'No restaurants found',
    'tag_connections': 'Tag connections',
    'no_mutual_connections': 'No mutual connections available to tag',
    'tag_loading_failed': 'Tag loading failed: {error}',
    'write_something': 'Write something',
    'select_product_category': 'Please select a product category',
    'select_service_category': 'Please select a service category',
    'enter_food_name': 'Please enter food name',
    'enter_valid_price': 'Please enter a valid price',
    'enter_product_price': 'Please enter product price',
    'select_food_category': 'Please select a food category',
    'paste_valid_youtube':
        'Please paste a valid YouTube link (youtube.com / youtu.be)',
    'location_required': 'Location required',
    'set_location_in_profile':
        'To post on Allonssy!, please set your location in your profile.',
    'error_with_detail': 'Error: {error}',
    'media': 'Media',
    'choose_photos': 'Choose photos',
    'replace_photos': 'Replace photos',
    'choose_video': 'Choose video',
    'replace_video': 'Replace video',
    'no_media': 'No media',
    'text_only': 'Text only',
    'photos': 'Photos',
    'video_file': 'Video file',
    'youtube_link': 'YouTube link',
    'one_video_from_gallery': '1 video from gallery',
    'one_youtube_only': '1 YouTube URL only',
    'video_selected': 'Video selected',
    'youtube_video_url': 'YouTube video URL',
    'create_post': 'Create Post',
    'what_is_happening': 'What is happening?',
    'selected_count': '{count} selected',
    'post_category': 'Post category',
    'food_name': 'Food name',
    'service_title': 'Service title',
    'product_title': 'Product title',
    'food_price_optional': 'Food price (optional)',
    'rate_budget_optional': 'Rate/Budget (optional)',
    'price': 'Price',
    'marketplace_type': 'Marketplace type',
    'selling': 'Selling',
    'buying': 'Buying',
    'product_category': 'Product category',
    'service_category': 'Service category',
    'food_category': 'Food category',
    'this_post_public_nearby':
        'This post will be public so everyone nearby can see it.',
    'post_now': 'Post now',
    'post_label': 'Post',
    'size_limit_photo': 'Size limit exceeded. Each photo must be under {mb} MB.',
    'only_n_photos': 'Only {count} photos can be attached to one post.',
    'quick_camera_post': 'Quick Camera Post',
    'camera_failed': 'Camera failed: {error}',
    'capture_something_first': 'Capture something first',
    'no_media_captured': 'No media captured',
    'retake': 'Retake',
    'this_quick_post_public': 'This quick camera post will be public.',
  };

  static const Map<String, String> _fr = {
    'startup_failed': 'Le demarrage a echoue',
    'home': 'Accueil',
    'search': 'Recherche',
    'chat': 'Chat',
    'alerts': 'Alertes',
    'options': 'Options',
    'filters': 'Filtres',
    'clear': 'Effacer',
    'marketplace': 'Marche',
    'gigs': 'Services',
    'foods': 'Plats',
    'businesses': 'Entreprises',
    'restaurants': 'Restaurants',
    'my_profile': 'Mon profil',
    'admin_portal': 'Portail admin',
    'logout': 'Deconnexion',
    'more': 'Plus',
    'notifications': 'Notifications',
    'messages': 'Messages',
    'logout_failed': 'Echec de deconnexion : {error}',
    'edit_profile': 'Modifier le profil',
    'edit_profile_intro':
        'Mettez a jour votre identite, vos categories, votre localisation et vos reglages du fil.',
    'tap_to_change_avatar': 'Touchez pour changer l avatar',
    'avatar_updated': 'Avatar mis a jour',
    'postal_code_locked':
        'Le code postal est verrouille apres le premier enregistrement.',
    'postal_code_required':
        'Entrez un code postal francais valide a 5 chiffres (ex. 91000)',
    'geocoding_failed':
        'La geolocalisation a echoue (HTTP {status}). Reessayez.',
    'postal_code_not_found':
        'Code postal introuvable. Essayez-en un autre.',
    'invalid_coordinates':
        'La geolocalisation a renvoye des coordonnees invalides. Essayez un autre code.',
    'location_set_city': 'Localisation definie pour {zip} • {city}',
    'location_set_zip_only':
        'Localisation definie pour {zip}. Ajoutez votre ville manuellement si besoin.',
    'not_logged_in': 'Non connecte',
    'name_required': 'Le nom est obligatoire',
    'set_location_first':
        'Veuillez d abord definir votre localisation (code postal)',
    'city_required': 'La ville est obligatoire',
    'select_org_type':
        'Veuillez selectionner Gouvernement, Association ou Agence de presse',
    'select_restaurant_type':
        'Veuillez selectionner un type de restaurant',
    'select_business_type':
        'Veuillez selectionner un type d entreprise',
    'saving': 'Enregistrement...',
    'save': 'Enregistrer',
    'account_type': 'Type de compte',
    'person': 'Particulier',
    'business': 'Entreprise',
    'organization': 'Organisation',
    'are_you_restaurant': 'Etes-vous un restaurant ?',
    'restaurant_category': 'Categorie du restaurant',
    'business_category': 'Categorie de l entreprise',
    'business_name': 'Nom de l entreprise',
    'organization_name': 'Nom de l organisation',
    'your_title': 'Votre fonction (Fondateur, Gerant, Manager...)',
    'short_business_profile': 'Courte presentation de l entreprise',
    'short_organization_profile': 'Courte presentation de l organisation',
    'describe_business': 'Decrivez brievement votre entreprise',
    'describe_organization': 'Decrivez brievement votre organisation',
    'organization_type': 'Type d organisation',
    'government': 'Gouvernement',
    'non_profit': 'Association',
    'news_agency': 'Agence de presse',
    'name': 'Nom',
    'bio_optional': 'Bio (optionnelle)',
    'postal_code': 'Code postal',
    'postal_code_hint': 'ex. 91000',
    'locked_after_first_set': 'Verrouille apres le premier enregistrement',
    'set': 'Definir',
    'set_done': 'Defini ✓',
    'city': 'Ville',
    'city_hint':
        'Rempli automatiquement depuis le code postal, ou saisissez-la manuellement',
    'city_lat_lng': 'Ville : {city} • Lat/Lng : {lat}, {lng}',
    'lat_lng': 'Lat/Lng : {lat}, {lng}',
    'feed_radius': 'Rayon du fil',
    'app_language': 'Langue de l application',
    'english': 'Anglais',
    'french': 'Francais',
    'public': 'Public',
    'share': 'Partager',
    'local': 'Local',
    'visibility': 'Visibilite',
    'no_sharing': 'Pas de partage',
    'followers_can_share': 'Les abonnes peuvent partager',
    'connections_can_share': 'Les relations peuvent partager',
    'public_can_share': 'Le public peut partager',
    'allow_sharing': 'Autoriser le partage',
    'complete_profile': 'Completer le profil',
    'profile': 'Profil',
    'profile_error': 'Erreur de profil :\n{error}',
    'type': 'Type : {value}',
    'location': 'Lieu : {value}',
    'followers': 'Abonnes',
    'following': 'Abonnements',
    'connections': 'Relations',
    'followers_following_private':
        'Les listes abonnes/abonnements sont privees.',
    'message': 'Message',
    'message_after_mutual_follow':
        'La messagerie est disponible quand vous vous suivez mutuellement.',
    'organization_government': 'Organisation • Gouvernement',
    'organization_nonprofit': 'Organisation • Association',
    'organization_news_agency': 'Organisation • Agence de presse',
    'restaurant': 'Restaurant',
    'profile_actions': 'Actions du profil',
    'follow_requests': 'Demandes de suivi',
    'follow_requests_pending': '{count} demandes en attente',
    'review_incoming_requests': 'Voir les demandes recues',
    'update_details_location':
        'Mettez a jour vos informations et votre localisation',
    'profile_settings': 'Parametres du profil',
    'manage_app_preferences':
        'Gerez les preferences de l application comme la lecture auto des videos',
    'followers_count_subtitle': '{count} personnes vous suivent',
    'following_count_subtitle': '{count} profils que vous suivez',
    'connections_count_subtitle':
        '{count} personnes vous suivent en retour',
    'my_products': 'Mes produits',
    'edit_delete_marketplace_ads':
        'Modifier ou supprimer vos annonces marketplace',
    'my_gigs': 'Mes services',
    'edit_delete_service_ads':
        'Modifier ou supprimer vos annonces de service',
    'my_foods': 'Mes plats',
    'edit_delete_food_ads': 'Modifier ou supprimer vos annonces food',
    'visible_only_own_profile': 'Visible seulement sur votre profil',
    'profile_overview': 'Vue du profil',
    'this_is_your_profile': 'Ceci est votre profil',
    'delete_post': 'Supprimer la publication ?',
    'delete_post_body':
        'Cela supprimera la publication de votre profil et du fil.',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'post_deleted': 'Publication supprimee.',
    'delete_failed': 'Echec de suppression : {error}',
    'follow_error': 'Erreur de suivi : {error}',
    'unfollow': 'Ne plus suivre',
    'requested': 'Demande envoyee',
    'request_again': 'Redemander',
    'request_follow': 'Demander a suivre',
    'remove_photo': 'Supprimer la photo ?',
    'remove_photo_body': 'Elle sera retiree de votre portfolio.',
    'remove': 'Retirer',
    'portfolio_error': 'Erreur de portfolio :\n{error}',
    'portfolio': 'Portfolio',
    'add': 'Ajouter',
    'add_portfolio_photos':
        'Ajoutez jusqu a 5 photos a votre portfolio.',
    'no_portfolio_photos': 'Pas encore de photos dans le portfolio.',
    'replace_photo': 'Remplacer la photo',
    'remove_photo_tooltip': 'Supprimer la photo',
    'portfolio_upload_error': 'Erreur d ajout au portfolio : {error}',
    'portfolio_delete_error': 'Erreur de suppression du portfolio : {error}',
    'portfolio_update_error': 'Erreur de mise a jour du portfolio : {error}',
    'playback': 'Lecture',
    'playback_subtitle':
        'Controlez le comportement des videos dans toute l application.',
    'video_auto_play': 'Lecture auto des videos',
    'video_auto_play_subtitle':
        'Les videos demarrent automatiquement si l option est activee.',
    'in_app_notifications': 'Notifications dans l application',
    'in_app_notifications_subtitle':
        'Choisissez les mises a jour affichees dans l application.',
    'push_notifications': 'Notifications push',
    'push_notifications_subtitle':
        'Enregistrees maintenant pour le futur support push mobile et web.',
    'failed_to_save_setting':
        'Echec de l enregistrement du parametre : {error}',
    'chat_messages': 'Messages chat',
    'chat_messages_subtitle':
        'Afficher des alertes en direct pour les messages prives.',
    'offer_messages': 'Messages d offre',
    'offer_messages_subtitle':
        'Afficher les notifications pour les messages de conversation d annonce.',
    'offer_updates': 'Mises a jour d offre',
    'offer_updates_subtitle':
        'Afficher les mises a jour d offre envoyee, acceptee et refusee.',
    'comments_on_my_posts': 'Commentaires sur mes publications',
    'comments_on_my_posts_subtitle':
        'Vous notifier quand quelqu un commente votre contenu.',
    'replies_to_my_comments': 'Reponses a mes commentaires',
    'replies_to_my_comments_subtitle':
        'Vous notifier quand quelqu un repond a votre commentaire ou question.',
    'mentions': 'Mentions',
    'mentions_subtitle':
        'Vous notifier quand quelqu un vous mentionne dans une publication ou un commentaire.',
    'follow_requests_subtitle':
        'Vous notifier quand quelqu un demande a vous suivre.',
    'new_followers': 'Nouveaux abonnes',
    'new_followers_subtitle':
        'Vous notifier quand quelqu un vous suit ou accepte votre demande.',
    'admin_and_safety_updates': 'Mises a jour admin et securite',
    'admin_and_safety_updates_subtitle':
        'Afficher les mises a jour liees au compte, a la moderation et a la securite.',
    'push_chat_messages': 'Push messages chat',
    'push_chat_messages_subtitle':
        'Reserve au futur support des notifications push mobile et web.',
    'push_offer_messages': 'Push messages d offre',
    'push_offer_messages_subtitle':
        'Reserve aux futures notifications push des chats d offre.',
    'push_offer_updates': 'Push mises a jour d offre',
    'push_offer_updates_subtitle':
        'Reserve aux push pour offres envoyees, acceptees et refusees.',
    'push_comments': 'Push commentaires',
    'push_comments_subtitle':
        'Reserve aux futures notifications push sur les commentaires.',
    'push_replies': 'Push reponses',
    'push_replies_subtitle':
        'Reserve aux futures notifications push sur les reponses.',
    'push_mentions': 'Push mentions',
    'push_mentions_subtitle':
        'Reserve aux futures notifications push sur les mentions.',
    'push_follow_requests': 'Push demandes de suivi',
    'push_follow_requests_subtitle':
        'Reserve aux futures notifications push sur les demandes de suivi.',
    'push_new_followers': 'Push nouveaux abonnes',
    'push_new_followers_subtitle':
        'Reserve aux futures notifications push sur les abonnements.',
    'push_admin_updates': 'Push admin et securite',
    'push_admin_updates_subtitle':
        'Reserve aux notifications push importantes admin et securite.',
    'account_disabled_contact_admin':
        'Ce compte a ete desactive. Contactez un administrateur.',
    'google_tokens_missing':
        'La connexion Google n a pas renvoye les jetons necessaires.',
    'sign_in_failed': 'Connexion impossible',
    'welcome_to': 'Bienvenue sur',
    'login_intro':
        'Actualites de quartier, bonnes affaires marketplace, services, annonces food et conversations locales au meme endroit.',
    'nearby_posts': 'Publications proches',
    'offer_chats': 'Chats d offre',
    'local_services': 'Services locaux',
    'welcome_back': 'Bon retour',
    'sign_in_to_network':
        'Connectez-vous pour revenir sur votre reseau local.',
    'email': 'Email',
    'password': 'Mot de passe',
    'forgot_password': 'Mot de passe oublie ?',
    'signing_in': 'Connexion...',
    'sign_in': 'Se connecter',
    'continue_with_google': 'Continuer avec Google',
    'create_account_cta': 'Creer un compte',
    'join': 'Rejoindre',
    'register_intro':
        'Creez votre compte et commencez a decouvrir les publications proches, les offres locales, les annonces food et les actualites de confiance.',
    'create_profile': 'Creer le profil',
    'share_locally': 'Partager localement',
    'find_nearby_deals': 'Trouver des offres proches',
    'chat_safely': 'Discuter en securite',
    'check_your_email': 'Verifiez votre email',
    'verification_email_sent':
        'Nous avons envoye un email de confirmation a {email}. Entrez le code a 6 chiffres ci-dessous, ou cliquez sur le lien dans l\'email.',
    'enter_verification_code': 'Entrez le code a 6 chiffres de votre email',
    'verification_code': 'Code de verification',
    'verify_email': 'Verifier',
    'verifying': 'Verification...',
    'verification_success': 'Email verifie ! Vous pouvez maintenant vous connecter.',
    'invalid_otp_code': 'Code invalide ou expire. Verifiez votre email et reessayez.',
    'return_to_login': 'Retour a la connexion',
    'create_account': 'Creer un compte',
    'start_local_profile':
        'Demarrez votre profil local en quelques secondes.',
    'creating': 'Creation...',
    'sign_up_failed': 'Inscription impossible',
    'email_exists_login':
        'Un compte avec cet email existe deja. Connectez-vous plutot.',
    'back_to_login': 'Retour a la connexion',
    'enter_email_address': 'Entrez votre adresse email',
    'reset_failed': 'Echec de reinitialisation : {error}',
    'reset_password': 'Reinitialiser votre mot de passe',
    'reset_password_intro':
        'Entrez l adresse email liee a votre compte.',
    'reset_link_sent_if_exists':
        'Si un compte existe pour {email}, vous recevrez bientot un lien de reinitialisation.',
    'sending': 'Envoi...',
    'send_reset_link': 'Envoyer le lien',
    'set_new_password': 'Definir un nouveau mot de passe',
    'set_new_password_intro':
        'Choisissez un mot de passe securise pour votre compte.',
    'password_min_length':
        'Le mot de passe doit contenir au moins 6 caracteres',
    'passwords_do_not_match':
        'Les mots de passe ne correspondent pas',
    'password_updated_successfully':
        'Mot de passe mis a jour avec succes',
    'new_password': 'Nouveau mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'update_password': 'Mettre a jour le mot de passe',
    'notifications_intro':
        'Restez a jour sur les suivis, messages, offres et mises a jour.',
    'mark_all_read': 'Tout marquer comme lu',
    'load_more_failed': 'Echec du chargement supplementaire : {error}',
    'failed_generic': 'Echec : {error}',
    'nothing_to_open': 'Rien a ouvrir',
    'request_accepted': 'Demande acceptee',
    'accept_failed': 'Echec de l acceptation : {error}',
    'request_declined': 'Demande refusee',
    'decline_failed': 'Echec du refus : {error}',
    'accept': 'Accepter',
    'decline': 'Refuser',
    'someone': 'Quelqu un',
    'seller': 'Vendeur',
    'author': 'Auteur',
    'notif_follow_request': '{name} a demande a vous suivre',
    'notif_follow_accepted': '{name} a accepte votre demande de suivi',
    'notif_follow': '{name} a commence a vous suivre',
    'notif_like': '{name} a aime votre publication',
    'notif_listing_question': '{name} a pose une question sur votre annonce',
    'notif_comment': '{name} a commente votre publication',
    'notif_comment_like': '{name} a aime votre commentaire',
    'notif_listing_reply': '{name} a repondu a votre question',
    'notif_comment_reply': '{name} a repondu a votre commentaire',
    'notif_share': '{name} a partage votre publication',
    'notif_tagged_comment': '{name} vous a mentionne dans un commentaire',
    'notif_tagged_post': '{name} vous a mentionne dans une publication',
    'notif_offer_message': '{name} a envoye un message sur votre annonce',
    'notif_offer_sent': '{name} a envoye une offre sur votre annonce',
    'notif_offer_accepted': '{name} a accepte l offre',
    'notif_offer_rejected': '{name} a refuse l offre',
    'notif_generic_update': '{name} a envoye une mise a jour',
    'unread': 'Non lu',
    'tap_to_open': 'Touchez pour ouvrir',
    'no_notifications_yet': 'Aucune notification pour le moment',
    'scroll_down_load_more': 'Faites defiler pour charger plus',
    'hide_search_filters': 'Masquer les filtres de recherche',
    'show_search_filters': 'Afficher les filtres de recherche',
    'profiles': 'Profils',
    'posts': 'Publications',
    'nearby_only': 'A proximite seulement',
    'loading_your_location': 'Chargement de votre position...',
    'global_search': 'Recherche globale',
    'location_not_set_fallback':
        'Position non definie dans votre profil (retour a la recherche globale)',
    'using_profile_radius': 'Rayon de votre profil utilise : {radius} km',
    'match_strictness': 'Precision de correspondance',
    'broad': 'Large',
    'balanced': 'Equilibre',
    'precise': 'Precis',
    'exact': 'Exact',
    'broader': 'Plus large',
    'this_changes_match_quality':
        'Cela change seulement la qualite de correspondance. La distance depend de "A proximite seulement".',
    'scope': 'Portee',
    'post_type': 'Type de publication',
    'author_type': 'Type d auteur',
    'retry': 'Reessayer',
    'type_something_to_search': 'Tapez quelque chose pour rechercher.',
    'no_profiles_found': 'Aucun profil trouve.',
    'unnamed': 'Sans nom',
    'no_posts_found': 'Aucune publication trouvee.',
    'no_text': '(pas de texte)',
    'search_profiles_or_posts': 'Rechercher des profils ou des publications...',
    'all': 'Tout',
    'service_offer': 'Offre',
    'service_request': 'Demande',
    'lost_found': 'Objets perdus et trouves',
    'post_shared': 'Publication partagee',
    'share_error': 'Erreur de partage : {error}',
    'like_error': 'Erreur de mention J aime : {error}',
    'discover_nearby': 'Decouvrir autour de vous',
    'feed_controls': 'Controles du fil',
    'close': 'Fermer',
    'reset': 'Reinitialiser',
    'general_posts': 'Publications generales',
    'normal_feed_posts_only': 'Publications normales du fil seulement.',
    'marketplace_posts': 'Publications marketplace',
    'buying_selling_product_categories':
        'Achats, ventes et categories de produits.',
    'marketplace_categories': 'Categories marketplace',
    'select_at_least_one_category': 'Selectionnez au moins une categorie.',
    'gig_posts': 'Publications de services',
    'service_offers_requests_and_categories':
        'Offres, demandes et categories de services.',
    'gig_type': 'Type de service',
    'offering': 'Offre',
    'requesting': 'Demande',
    'service_categories': 'Categories de services',
    'lost_and_found': 'Objets perdus et trouves',
    'show_or_hide_lost_and_found_posts':
        'Afficher ou masquer les publications d objets perdus et trouves.',
    'food_ads': 'Annonces food',
    'food_posts_with_separate_categories':
        'Publications food avec categories separees.',
    'organization_types': 'Types d organisation',
    'show_organization_posts_by_subtype':
        'Afficher les publications d organisations par sous-type.',
    'select_at_least_one_type': 'Selectionnez au moins un type.',
    'apply_filters': 'Appliquer les filtres',
    'visibility_public_following': 'Public + Abonnements',
    'browse_sections': 'Parcourir les sections',
    'open_filters': 'Ouvrir les filtres',
    'post_to_feed': 'Publier dans le fil',
    'reset_feed': 'Reinitialiser le fil',
    'local_directory': 'Annuaire local',
    'browse_nearby_places_to_eat': 'Parcourez les endroits proches ou manger.',
    'explore_nearby_local_businesses':
        'Explorez les entreprises locales a proximite.',
    'top_trending': 'Top tendances',
    'no_top_posts_yet': 'Pas encore de publications en tete',
    'engagement_count': '{count} interactions',
    'todo': 'A faire',
    'review_offers': 'Voir les offres',
    'conversations_need_attention':
        '{count} conversations demandent votre attention.',
    'unread_offer_messages': 'Messages d offre non lus',
    'unread_messages_in_offer_chats':
        '{count} messages non lus dans les chats d offre.',
    'unread_notifications': '{count} notifications non lues.',
    'unread_chats': 'Chats non lus',
    'unread_conversations': '{count} conversations non lues.',
    'nothing_pending_right_now': 'Rien en attente pour le moment.',
    'profile_completeness': 'Profil complete',
    'profile_complete_percent': '{count}% complete',
    'improve_trust_and_discovery':
        'Ajoutez les informations manquantes pour ameliorer la confiance et la decouverte.',
    'open_profile': 'Ouvrir le profil',
    'open_original': 'Ouvrir l original',
    'feed_error': 'Erreur du fil :\n{error}',
    'no_sections_selected': 'aucune section selectionnee',
    'you_are_seeing': 'Vous voyez {sections}',
    'you_are_seeing_with_radius':
        'Vous voyez {sections}. Le rayon des publications publiques est defini dans le profil : {radius} km',
    'all_marketplace_posts': 'toutes les publications marketplace',
    'no_categories_selected': 'aucune categorie selectionnee',
    'all_gigs': 'tous les services',
    'gigs_in_categories': 'services {types} dans {categories}',
    'food_ads_in_categories': 'annonces food dans {categories}',
    'all_organization_posts': 'toutes les publications d organisation',
    'sell_buy': 'Vendre / Acheter',
    'search_products_category_seller':
        'Rechercher des produits, categorie, vendeur...',
    'category_label': 'Categorie :',
    'type_label': 'Type :',
    'sort_label': 'Tri :',
    'all_categories': 'Toutes les categories',
    'all_types': 'Tous les types',
    'newest_first': 'Plus recentes d abord',
    'oldest_first': 'Plus anciennes d abord',
    'price_low_to_high': 'Prix : du plus bas au plus haut',
    'price_high_to_low': 'Prix : du plus haut au plus bas',
    'no_marketplace_posts_found': 'Aucune publication marketplace trouvee',
    'looking_to_buy': 'Recherche a acheter',
    'price_on_request': 'Prix sur demande',
    'post_a_service': 'Publier un service',
    'search_services_category_provider':
        'Rechercher des services, categorie, prestataire...',
    'with_price': 'Avec prix',
    'without_price': 'Sans prix',
    'no_service_posts_found': 'Aucune publication de service trouvee',
    'budget_open': 'Budget ouvert',
    'rate_on_request': 'Tarif sur demande',
    'send_offer': 'Envoyer une offre',
    'search_foods_category_restaurant':
        'Rechercher des plats, categorie, restaurant...',
    'all_food_categories': 'Toutes les categories food',
    'sort_by': 'Trier par',
    'no_food_ads_found': 'Aucune annonce food trouvee',
    'search_businesses': 'Rechercher des entreprises...',
    'distance_label': 'Distance :',
    'no_businesses_found': 'Aucune entreprise trouvee',
    'search_restaurants': 'Rechercher des restaurants...',
    'no_restaurants_found': 'Aucun restaurant trouve',
    'tag_connections': 'Identifier des relations',
    'no_mutual_connections':
        'Aucune relation mutuelle disponible a identifier',
    'tag_loading_failed': 'Echec du chargement des tags : {error}',
    'write_something': 'Ecrivez quelque chose',
    'select_product_category':
        'Veuillez selectionner une categorie de produit',
    'select_service_category':
        'Veuillez selectionner une categorie de service',
    'enter_food_name': 'Veuillez entrer le nom du plat',
    'enter_valid_price': 'Veuillez entrer un prix valide',
    'enter_product_price': 'Veuillez entrer le prix du produit',
    'select_food_category':
        'Veuillez selectionner une categorie de nourriture',
    'paste_valid_youtube':
        'Veuillez coller un lien YouTube valide (youtube.com / youtu.be)',
    'location_required': 'Localisation requise',
    'set_location_in_profile':
        'Pour publier sur Allonssy!, veuillez definir votre localisation dans votre profil.',
    'error_with_detail': 'Erreur : {error}',
    'media': 'Media',
    'choose_photos': 'Choisir des photos',
    'replace_photos': 'Remplacer les photos',
    'choose_video': 'Choisir une video',
    'replace_video': 'Remplacer la video',
    'no_media': 'Pas de media',
    'text_only': 'Texte seulement',
    'photos': 'Photos',
    'video_file': 'Fichier video',
    'youtube_link': 'Lien YouTube',
    'one_video_from_gallery': '1 video depuis la galerie',
    'one_youtube_only': '1 URL YouTube uniquement',
    'video_selected': 'Video selectionnee',
    'youtube_video_url': 'URL de la video YouTube',
    'create_post': 'Creer une publication',
    'what_is_happening': 'Que se passe-t-il ?',
    'selected_count': '{count} selectionnes',
    'post_category': 'Categorie de publication',
    'food_name': 'Nom du plat',
    'service_title': 'Titre du service',
    'product_title': 'Titre du produit',
    'food_price_optional': 'Prix du plat (optionnel)',
    'rate_budget_optional': 'Tarif/Budget (optionnel)',
    'price': 'Prix',
    'marketplace_type': 'Type marketplace',
    'selling': 'Vente',
    'buying': 'Achat',
    'product_category': 'Categorie de produit',
    'service_category': 'Categorie de service',
    'food_category': 'Categorie de nourriture',
    'this_post_public_nearby':
        'Cette publication sera publique pour que tout le monde a proximite puisse la voir.',
    'post_now': 'Publier maintenant',
    'post_label': 'Publier',
    'size_limit_photo':
        'Limite depassee. Chaque photo doit faire moins de {mb} MB.',
    'only_n_photos':
        'Seulement {count} photos peuvent etre jointes a une publication.',
    'quick_camera_post': 'Publication camera rapide',
    'camera_failed': 'Echec de la camera : {error}',
    'capture_something_first': 'Capturez quelque chose d abord',
    'no_media_captured': 'Aucun media capture',
    'retake': 'Reprendre',
    'this_quick_post_public':
        'Cette publication camera rapide sera publique.',
  };

  String tr(String key, {Map<String, String> args = const {}}) {
    final table = isFrench ? _fr : _en;
    var value = table[key] ?? _en[key] ?? key;
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales
          .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsBuildContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
